CREATE TABLE Film (
	TITLU VARCHAR(50) NOT NULL,
	AN NUMBER NOT NULL,
	DURATA NUMBER NOT NULL,
	GEN VARCHAR(10) NOT NULL,
	STUDIO VARCHAR(50) NOT NULL,
	ID_PRODUCATOR NUMBER NOT NULL);

CREATE TABLE Distributie (
	TITLU_FILM VARCHAR(50) NOT NULL,
	AN_FILM NUMBER NOT NULL,
	ID_ACTOR NUMBER NOT NULL);

CREATE TABLE Persoana (
	ID_PERSOANA NUMBER NOT NULL,
	NUME VARCHAR(50) NOT NULL,
	ADRESA VARCHAR(50) NOT NULL,
	SEX CHAR(1) NOT NULL,
	DATA_NASTERII DATE NOT NULL,
	CASTIG_NET NUMBER NOT NULL,
	MONEDA VARCHAR(3) NOT NULL);

CREATE TABLE Studio (
	NUME VARCHAR(50) NOT NULL,
	ADRESA VARCHAR(50) NOT NULL,
	TARA VARCHAR(20) NOT NULL,
	ID_PRESEDINTE NUMBER NOT NULL);


INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (100,'Mirel','Principala 20','M',to_date('09/23/1986','mm/dd/yyyy'),43243,'EUR');
INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (101,'Florina','Principala 21','F',to_date('02/13/1982','mm/dd/yyyy'),214343,'GBP');
INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (105,'Alina','Zorilor 2','F',to_date('06/23/2000','mm/dd/yyyy'),2444,'GBP');
INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (102,'Florin','Principala 31','M',to_date('12/03/1999','mm/dd/yyyy'),111243,'USD');
INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (103,'Andreea','Principala 31','F',to_date('12/03/1999','mm/dd/yyyy'),12000243,'USD');
INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (22,'Humphrey Bogart','Principala 235','M',to_date('09/02/1954','mm/dd/yyyy'),5756243,'EUR');

INSERT INTO Studio (NUME,ADRESA,TARA,ID_PRESEDINTE) values ('EA','32 Buftea Bucuresti','Romania',100);
INSERT INTO Studio (NUME,ADRESA,TARA,ID_PRESEDINTE) values ('ABCCD','15 NY','USA',100);
INSERT INTO Studio (NUME,ADRESA,TARA,ID_PRESEDINTE) values ('Disney','20 Colorado','USA',105);
	
INSERT INTO Film (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('Iron Man 1',1988,210,'SF','EA',100);
INSERT INTO Film (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('Iron Man 2',2009,220,'SF','EA',101);
INSERT INTO Film (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('Iron Man 3',2010,230,'SF','EA',100);
INSERT INTO Film (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('Friends',2000,150,'comedie','ABCCD',22);
INSERT INTO FILM (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('CAN',1999,100,'SF','ABCCD',22);
INSERT INTO FILM (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('Mickey Mouse',2005,130,'copii','Disney',105);

INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 3',2010,100);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 3',2010,101);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 3',2010,102);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 2',2009,101);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 2',2009,103);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 1',1988,103);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 1',1988,102);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Friends',2000,101);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Friends',2000,103);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Friends',2000,102);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Mickey Mouse',2005,22);

ALTER TABLE Film ADD CONSTRAINT PK_Film PRIMARY KEY(TITLU, AN);

ALTER TABLE Persoana ADD CONSTRAINT PK_Persoana PRIMARY KEY(ID_PERSOANA);

ALTER TABLE Studio ADD CONSTRAINT PK_Studio PRIMARY KEY(NUME);

ALTER TABLE Distributie ADD CONSTRAINT PQ_Distributie 	PRIMARY KEY(TITLU_FILM, AN_FILM, ID_ACTOR);

ALTER TABLE Distributie ADD 
	CONSTRAINT FK_Distributie1 FOREIGN KEY (ID_ACTOR) 
	REFERENCES Persoana(ID_PERSOANA) ON DELETE CASCADE;

ALTER TABLE Distributie ADD 
	CONSTRAINT FK_Distributie2 FOREIGN KEY (TITLU_FILM, AN_FILM) 
	REFERENCES Film (TITLU,AN) ON DELETE CASCADE;

ALTER TABLE Film ADD 
	CONSTRAINT FK_Film1 FOREIGN KEY (ID_PRODUCATOR) 
	REFERENCES Persoana(ID_PERSOANA) ON DELETE CASCADE;

ALTER TABLE Studio ADD 
	CONSTRAINT FK_Studio FOREIGN KEY (ID_PRESEDINTE) 
	REFERENCES Persoana(ID_PERSOANA) ON DELETE CASCADE;

ALTER TABLE Film ADD 
	CONSTRAINT FK_Film2 FOREIGN KEY (STUDIO) 
	REFERENCES Studio(NUME) ON DELETE CASCADE;

ALTER TABLE Persoana ADD
	CONSTRAINT CK_persoana_moneda CHECK (MONEDA = 'USD' or
                          MONEDA = 'EUR' or MONEDA = 'GBP');

ALTER TABLE Film ADD
	CONSTRAINT CK_Film_gen CHECK (GEN IN ('SF','copii','drama','comedie'));

ALTER TABLE Persoana ADD (email VARCHAR(50));


--9.2
ALTER TABLE Persoana ADD CONSTRAINT CK_Persoana_sex CHECK (SEX IN ('M', 'F'));

ALTER TABLE Studio ADD CONSTRAINT CK_Studio_adresa
	 CHECK ((ADRESA LIKE '%Buftea%' AND TARA='Romania') or ADRESA NOT LIKE '%Buftea%');


INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (100,'Mirel','Principala 20','M',to_date('09/23/1986','mm/dd/yyyy'),43243,'EUR');
INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (101,'Florina','Principala 21','F',to_date('02/13/1982','mm/dd/yyyy'),214343,'GBP');
INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (105,'Alina','Zorilor 2','F',to_date('06/23/2000','mm/dd/yyyy'),2444,'GBP');
INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (102,'Florin','Principala 31','M',to_date('12/03/1999','mm/dd/yyyy'),111243,'USD');
INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (103,'Andreea','Principala 31','F',to_date('12/03/1999','mm/dd/yyyy'),12000243,'USD');
INSERT INTO Persoana (ID_PERSOANA,NUME,ADRESA,SEX,DATA_NASTERII,CASTIG_NET,MONEDA) values (22,'Humphrey Bogart','Principala 235','M',to_date('09/02/1954','mm/dd/yyyy'),5756243,'EUR');

INSERT INTO Studio (NUME,ADRESA,TARA,ID_PRESEDINTE) values ('EA','32 Buftea Bucuresti','Romania',100);
INSERT INTO Studio (NUME,ADRESA,TARA,ID_PRESEDINTE) values ('ABCCD','15 NY','USA',100);
INSERT INTO Studio (NUME,ADRESA,TARA,ID_PRESEDINTE) values ('Disney','20 Colorado','USA',105);
	
INSERT INTO Film (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('Iron Man 1',1988,210,'SF','EA',100);
INSERT INTO Film (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('Iron Man 2',2009,220,'SF','EA',101);
INSERT INTO Film (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('Iron Man 3',2010,230,'SF','EA',100);
INSERT INTO Film (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('Friends',2000,150,'comedie','ABCCD',22);
INSERT INTO FILM (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('CAN',1999,100,'SF','ABCCD',22);
INSERT INTO FILM (TITLU,AN,DURATA,GEN,STUDIO,ID_PRODUCATOR) values ('Mickey Mouse',2005,130,'copii','Disney',105);

INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 3',2010,100);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 3',2010,101);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 3',2010,102);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 2',2009,101);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 2',2009,103);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 1',1988,103);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Iron Man 1',1988,102);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Friends',2000,101);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Friends',2000,103);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Friends',2000,102);
INSERT INTO Distributie (TITLU_FILM,AN_FILM,ID_ACTOR) values ('Mickey Mouse',2005,22);